### ISSUE TITLE
Add option to add x-api-key header at awsserverless structure

### ISSUE THREAD

**Issue by utisam** [WorksApplications/swagger-code-builder#10]
Add securityDefinitions.

```
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
```

Add security to operation object.

```
    security:
      - api_key: []
```
